---
title       : FDIG 
subtitle    : Ferramentas Digitais para uma Ciência Aberta e com grandes quantidades de dados
author      : Alexandre Camargo Martensen
job         : CCN - Lagoa do Sino - UFSCar
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## O que iremos abordar?

1. Ciência aberta, dados abertos, metadados, códigos, erros e acertos ao longo do processo de descoberta científica, “pré-prints”, "peer review”, publicação aberta;
2. Grandes quantidades de dados, obtenção, organização, armazenamento e recuperação de dados; 
3. Desenvolvimento de scripts para organização, análise e geração de figuras e gráficos; 
4. Boas práticas na computação científica; 
5. Ferramentas digitais para fomentar a colaboração entre cientistas; 
6. Organização de projetos científicos; 
7. Controle de versão - git e gitHub;  
8. Categorias de softwares livres e diferentes tipos de licenças; 
9. Mídias sociais para divulgação de trabalhos, colaboração online, discussões científicas; 
10. Presença online; 
11. Perspectivas para a divulgação e comunicação científica nos próximos anos;

outros temas relacionados...

--- .class #id 

## O que não iremos fazer?

1. Aprender a trabalhar no R
    Você já deve saber o mínimo de R para participar dessa disciplina

2. 




